added the menu bar component
Redback-Operations/redback-ui pull request #31
Opened 2024-09-23 12:40 UTC by Danny6224

## Summary

What is the nature of this pull request?

- [x] New feature
- [ ] Enhancement to an existing feature
- [ ] Bug fix
- [ ] Configuration update
- [ ] Dependency update

### Description of change

Implemented a responsive Menu Bar Component for Redback UI, featuring navigation links, a dropdown menu, and a hamburger menu for mobile devices. The component follows accessibility guidelines, including keyboard navigation. Styled Components were used for styling, and unit tests have been added to ensure functionality.

### Planner card link
https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/tt.c_19:c1b94839a3db4c6e8bf052aeadb33d9b@thread.tacv2_p_TOGdCftBI0mZ937fEIW0jsgAHPsL_h_1710632381880?tenantId=d02378ec-1688-46d5-8540-1c28b5f470f6&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2FTOGdCftBI0mZ937fEIW0jsgAHPsL%2Ftask%2FcuDQV948JUSITMLQeoou48gAH9vc%22%2C%22channelId%22%3A%2219%3Ac1b94839a3db4c6e8bf052aeadb33d9b%40thread.tacv2%22%7D 

## Readiness

- [x] The application runs successfully with my change.
- [x] I have included [code comments](https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/) where appropriate.
- [ ] Where I have copied and pasted code from other sources, I have included a comment with a link to the original source.
- [x] I have read and followed the [principles and guidelines about submitting code](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/submitting-work).
- [x] I have added [unit tests](https://redback-operations.github.io/redback-documentation/docs/web-mobile-app-dev/frontend/tests) for new components and/or functionality.
- [ ] All existing and new unit tests pass (including updating tests for any necessary breaking changes).

2024-09-23 13:15 UTC, doubleedesign requested changes
Looking good so far! Main thing I think needs to be done before merge is updating values for colours, typography, and spacing to be retrieved from the active theme rather than hard-coded.

Ideally we should be rendering React Router links instead of plain HTML links, but that can be done in a follow-up task next trimester. 

There is also room for improvement in the HTML structure (I noted about `nav` but also just noticed there's no `ul` or `li`s, and the hamburger icon should have an accessible label) but these things would make a good first task for someone next trimester if you don't have time to refine these things this tri. :)

2024-09-23 13:15 UTC, doubleedesign commented on src/components/MenuBar/MenuBar.style.ts
> +	background-color: #e97462; /* Primary Color */
Please use the theme colours throughout. Syntax example:
`background-color: ${props => props.theme.colors.primary};`

2024-09-23 13:15 UTC, doubleedesign commented on src/components/MenuBar/MenuBar.style.ts
> +export const StyledMenuBar = styled.div`
Non-blocking thought: Maybe this could be a HTML `nav` element rather than a `div`?

2024-09-23 13:15 UTC, doubleedesign commented on src/components/MenuBar/MenuBar.style.ts
> +	font-family: 'Inter Tight', sans-serif; /* Font Family */
Please use theme values for font family, font size, font weight, padding, and margins throughout. You can find all the available theme values [here in the default theme definition](https://github.com/Redback-Operations/redback-ui/blob/main/src/themes/default.ts).

2024-10-28 06:53 UTC, ben-AI-cybersec approved these changes
All requested changes have been completed

2024-10-28 06:53 UTC, merged